### ISSUE TITLE
Crash when trying to empty Vial [ v. Vials-MC1.10.2-1.2.1.5.jar ]

### ISSUE THREAD

**Issue by Kyrnterra** [MightyPirates/Vials#8]
Game crashes when I attempted to empty a 16 mb vial of Blood (Biome O' Plenty fluid, I think, made it by smelting rotten flesh in a smeltery) into a Ender IO Fluid Tank.

Also when I use JEI to check for uses on the vials, the only options I have for emptying or filling the vials of any size is either the Fluid Tank from Ender IO or the Bottler from Forestry, though I guess that is the limit by my mod selection.

I can try to post the whole log if requested.

~~~~~

java.lang.NullPointerException: Ticking block entity
	at net.minecraftforge.fluids.capability.templates.FluidHandlerItemStack.setFluid(FluidHandlerItemStack.java:80)
	at li.cil.vials.common.item.ItemVial$1.drain(ItemVial.java:89)
	at com.enderio.core.common.util.FluidUtil.tryDrainContainer(FluidUtil.java:195)
	at com.enderio.core.common.util.FluidUtil.tryDrainContainer(FluidUtil.java:239)
	at crazypants.enderio.machine.tank.TileTank.drainFullContainer(TileTank.java:287)
	at crazypants.enderio.machine.tank.TileTank.processItems(TileTank.java:203)
	at crazypants.enderio.machine.tank.TileTank.processTasks(TileTank.java:160)
	at crazypants.enderio.machine.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:227)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:40)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by lordjoda** [comment]
Thanks for reporting. Sorry for the long delay. Will fix asap
